#li = ["ABSCENT", "ABSCENT",	ABSCENT, ABSCENT, PRESENT, PRESENT, PRESENT, PRESENT, ABSCENT, PRESENT, PRESENT, ABSCENT, PRESENT,	ABSCENT, PRESENT,	ABSCENT, PRESENT, ABSCENT, PRESENT, PRESENT, ABSCENT, PRESENT, ABSCENT,	ABSCENT, PRESENT, ABSCENT,	PRESENT, PRESENT, PRESENT, ABSCENT,ABSCENT, ABSCENT, ABSCENT, ABSCENT, ABSCENT, ABSCENT]
#a = "ABSCENTABSCENT,ABSCENTABSCENTPRESENT, PRESENT, PRESENT, PRESENT, ABSCENT, PRESENT, PRESENT, ABSCENT, PRESENT,	ABSCENT, PRESENT,	ABSCENT, PRESENT, ABSCENT, PRESENT, PRESENT, ABSCENT, PRESENT, ABSCENT,	ABSCENT, PRESENT, ABSCENT,	PRESENT, PRESENT, PRESENT, ABSCENT,ABSCENT, ABSCENT, ABSCENT, ABSCENT, ABSCENT, ABSCENT"
#a.replace(" ", "")
li = ["ABSCENT", "ABSCENT", "ABSCENT", "ABSCENT", "PRESENT", "PRESENT", "PRESENT", "PRESENT", "ABSCENT", "PRESENT", "PRESENT", "ABSCENT", "PRESENT", "ABSCENT", "PRESENT", "ABSCENT", "PRESENT", "ABSCENT", "PRESENT", "PRESENT", "ABSCENT", "PRESENT",
      "ABSCENT", "ABSCENT", "PRESENT", "ABSCENT", "PRESENT", "PRESENT", "PRESENT", "ABSCENT", "	ABSCENT", "ABSCENT", "ABSCENT", "ABSCENT", "ABSCENT", "ABSCENT", "ABSCENT", "ABSCENT", "PRESENT", "ABSCENT", "ABSCENT", "ABSCENT",	"ABSCENT", "ABSCENT"]

count = 0
for x in li:
    if x == "present":
        count += 1
print(count)
